mesh_files:
  link0:
    visual:
      mesh: "package://symphony_description/meshes/symphony40/visual/symphony40_0_w.dae"
      #mesh: "package://symphony_description/meshes/symphony40/visual/symphony40_0_w.dae"
      material: ""
    collision:
      mesh: "package://symphony_description/meshes/symphony40/collision/symphony40_0_s.stl"
  link1:
    visual:
      mesh: "package://symphony_description/meshes/symphony40/visual/symphony40_1_w.dae"
      #mesh: "package://symphony_description/meshes/symphony40/visual/symphony40_1_w.dae"
      material: ""
    collision:
      mesh: "package://symphony_description/meshes/symphony40/collision/symphony40_1_s.stl"
  link2:
    visual:
      mesh: "package://symphony_description/meshes/symphony40/visual/symphony40_2_w.dae"
      #mesh: "package://symphony_description/meshes/symphony40/visual/symphony40_2_w.dae"
      material: ""
    collision:
      mesh: "package://symphony_description/meshes/symphony40/collision/symphony40_2_s.stl"
  link3:
    visual:
      mesh: "package://symphony_description/meshes/symphony40/visual/symphony40_3_w.dae"
      #mesh: "package://symphony_description/meshes/symphony40/visual/symphony40_3_w.dae"
      material: ""
    collision:
      mesh: "package://symphony_description/meshes/symphony40/collision/symphony40_3_s.stl"
  link4:
    visual:
      mesh: "package://symphony_description/meshes/symphony40/visual/symphony40_4_w.dae"
      #mesh: "package://symphony_description/meshes/symphony40/visual/symphony40_4_w.dae"
      material: ""
    collision:
      mesh: "package://symphony_description/meshes/symphony40/collision/symphony40_4_s.stl"
  link5:
    visual:
      mesh: "package://symphony_description/meshes/symphony40/visual/symphony40_5_w.dae"
      #mesh: "package://symphony_description/meshes/symphony40/visual/symphony40_5_w.dae"
      material: ""
    collision:
      mesh: "package://symphony_description/meshes/symphony40/collision/symphony40_5_s.stl"
  link6:
    visual:
      mesh: "package://symphony_description/meshes/symphony40/visual/symphony40_6_w.dae"
      #mesh: "package://symphony_description/meshes/symphony40/visual/symphony40_6_w.dae"
      material: ""
    collision:
      mesh: "package://symphony_description/meshes/symphony40/collision/symphony40_6_s.stl"
